# Generated by Django 4.2.1 on 2023-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('number', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Описания продукта ')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
    ]
