# Generated by Django 4.2.1 on 2023-05-28 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('personal_num', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Персональный счет')),
                ('number', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Номер телефона')),
                ('tariff_start', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начала тарифа')),
                ('tariff_end', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Конец тарифа')),
                ('owner', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
