# Generated by Django 4.2.1 on 2023-05-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highway',
            new_name='Tariff',
        ),
    ]
